import { useEffect, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { Banknote, CreditCard, X } from 'lucide-react';
import QRPayment from './QRPayment';
import CashPayment from './CashPayment';

export default function PaymentModal({ booking, onClose, onSuccess }) {
  const [step, setStep] = useState('methods');
  useEffect(() => { const closeOnEscape = (event) => event.key === 'Escape' && onClose(); document.addEventListener('keydown', closeOnEscape); return () => document.removeEventListener('keydown', closeOnEscape); }, [onClose]);
  const close = () => setStep('methods');
  return <AnimatePresence><motion.div className="payment-modal-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onMouseDown={(event) => event.target === event.currentTarget && onClose()}><motion.div className={`payment-modal ${step !== 'methods' ? 'is-flow' : ''}`} initial={{ opacity: 0, scale: 0.96, y: 18 }} animate={{ opacity: 1, scale: 1, y: 0 }} exit={{ opacity: 0, scale: 0.96, y: 18 }} transition={{ type: 'spring', damping: 24, stiffness: 280 }} role="dialog" aria-modal="true" aria-label="Choose payment method"><button className="payment-close" type="button" onClick={onClose} aria-label="Close payment dialog"><X size={21} /></button><AnimatePresence mode="wait">{step === 'methods' ? <motion.section key="methods" className="payment-methods" initial={{ opacity: 0, x: -8 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: 8 }}><span className="payment-modal-kicker">Secure checkout</span><h2>How would you like to pay?</h2><p>Choose a payment route for <strong>NPR {Number(booking.amount || 0).toLocaleString()}</strong>.</p><div className="payment-option-list"><button type="button" className="payment-option" onClick={() => setStep('qr')}><span><CreditCard size={25} /></span><div><strong>QR Payment</strong><small>Scan and upload payment proof</small></div><i>→</i></button><button type="button" className="payment-option" onClick={() => setStep('cash')}><span><Banknote size={25} /></span><div><strong>Cash Payment</strong><small>Pay at the venue and submit your booking</small></div><i>→</i></button></div></motion.section> : step === 'qr' ? <motion.div key="qr" initial={{ opacity: 0, x: 12 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -12 }}><QRPayment booking={booking} onCancel={close} onSuccess={onSuccess} /></motion.div> : <motion.div key="cash" initial={{ opacity: 0, x: 12 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -12 }}><CashPayment booking={booking} onCancel={close} onSuccess={onSuccess} /></motion.div>}</AnimatePresence></motion.div></motion.div></AnimatePresence>;
}
